language: python
python:
 - 3.5
 - 3.6
 - 3.7
script:
 - python rnaindel/tests/test_indel_equivalence.py
 - python rnaindel/tests/test_sequence_properties.py
 - python rnaindel/tests/test_most_common.py
